language: java
after_success:
- "./gradlew jacocoTestReport coveralls"
- "./gradlew groovydoc buildSite"
- ".travis/deploy_ghpages.sh"
- ".travis/upload_nexus.sh"
env:
  global:
  - GH_REF: github.com/aweigold/lemming.git
  - secure: fxyMVivubZL7FcMDWC+4nRYSkWhr13yxarRza7z+jGvkzpoWvgZGUg9m4JoiOwZXE5Yf5rI3xznQuxMWNs8jFqgFWqbYA+3wpsdyAnzlcxTwILhqvaKVch8F5tMx3B9MUj/GMj5uw466yBKqJ3Ulokbutq/dysAheZY34G4xovM=
  - secure: I3Remkvzl3hXqiSCUzUOjfVhJTZl6Yd+Dh3ebtSqR3u9onzKK9rH4ja9Ossnqcnemty2zidJtbIYbpOmelyvK74WCz9pn0crDC9gYo8OBi6SRQZHqn8IbaN0EKEpH1JlFjuq/wnJ/NhfdlX6mFkMuSw+q414yFpMmthjBZoB+v0=
  - secure: d/NeT3JPqWQbiOPiNwALQSQk9dvdOQPA3/FUUFXQwzxrRye0IoAgdg1N1J4izXb7kmxDX/kN95LK0beXhnQFCQ9ijt2F/9dviDViYMB+zR8n26oaYK5CQAkhqui+rCQ2/1FqL3v8T8w834fv8U8vWHKYBUd9GyZ/+s10+yMzyrA=
  - secure: OBDA71iFuNsFCvCIz/XfhvgJ5BpRA+jY3TGXxHfMHOgQiZSDQzq4Gk8q9Fgo+Q72V7ukmdcx9a5EZXRcrskUVtg9dT2TXwcFJcWJuuwumsS9Ct9QGmlvTTv4gXiU6sYI6eBAzXZD5jOsiIdiJ1t/ROlaK1VhCdES4vRc55+UpdI=
